# Use the official Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /src

# Copy all files from the current directory to the container
COPY . /src

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Flask runs on
EXPOSE 8080

# Command to run the application
CMD ["python", "TranslateAPI.py"]